namespace TextToSqlAgent.Core.Models;

public class AgentResponse
{
    public bool Success { get; set; }
    public string Answer { get; set; } = string.Empty;
    public string? SqlGenerated { get; set; }
    public SqlExecutionResult? QueryResult { get; set; }
    public string? ErrorMessage { get; set; }
    public List<string> ProcessingSteps { get; set; } = new();

    // Self-correction tracking
    public List<CorrectionAttempt> CorrectionHistory { get; set; } = new();
    public bool WasCorrected { get; set; }
    public int CorrectionAttempts { get; set; }

    // NEW: Agentic AI enhancements
    /// <summary>
    /// Natural language explanation of the SQL query
    /// </summary>
    public string? QueryExplanation { get; set; }

    /// <summary>
    /// Query validation result
    /// </summary>
    public QueryValidationResult? ValidationResult { get; set; }

    /// <summary>
    /// Conversation ID for multi-turn support
    /// </summary>
    public string? ConversationId { get; set; }

    /// <summary>
    /// Whether this was a follow-up question
    /// </summary>
    public bool IsFollowUp { get; set; }

    /// <summary>
    /// Suggested follow-up queries generated by LLM
    /// </summary>
    public List<string> SuggestedQueries { get; set; } = new();
}