namespace TextToSqlAgent.Core.Models;

public class AgentResponse
{
    public bool Success { get; set; }
    public string Answer { get; set; } = string.Empty;
    public string? SqlGenerated { get; set; }
    public SqlExecutionResult? QueryResult { get; set; }
    public string? ErrorMessage { get; set; }
    public List<string> ProcessingSteps { get; set; } = new();

    // Self-correction tracking
    public List<CorrectionAttempt> CorrectionHistory { get; set; } = new();
    public bool WasCorrected { get; set; }
    public int CorrectionAttempts { get; set; }

    // NEW: Agentic AI enhancements
    /// <summary>
    /// Natural language explanation of the SQL query
    /// </summary>
    public string? QueryExplanation { get; set; }

    /// <summary>
    /// Query validation result
    /// </summary>
    public QueryValidationResult? ValidationResult { get; set; }

    /// <summary>
    /// Conversation ID for multi-turn support
    /// </summary>
    public string? ConversationId { get; set; }

    /// <summary>
    /// Whether this was a follow-up question
    /// </summary>
    public bool IsFollowUp { get; set; }

    /// <summary>
    /// Suggested follow-up queries generated by LLM
    /// </summary>
    public List<string> SuggestedQueries { get; set; } = new();

    // ✅ NEW: Context awareness fields for pronoun resolution
    /// <summary>
    /// Entities (tables) referenced in conversation context
    /// </summary>
    public List<string> ContextEntities { get; set; } = new();

    /// <summary>
    /// Primary entity being queried
    /// </summary>
    public string? PrimaryEntity { get; set; }

    /// <summary>
    /// Whether pronouns were detected and resolved
    /// </summary>
    public bool PronounsResolved { get; set; }

    /// <summary>
    /// Additional metadata for specialized responses (Forbidden, Write, DDL)
    /// </summary>
    public Dictionary<string, object>? Metadata { get; set; }

    // ✅ NEW: Data Visualization (Python sidecar Phase 2)
    /// <summary>
    /// Base64 encoded PNG chart image generated from query results.
    /// Frontend should render as: &lt;img src="data:image/png;base64,{ChartImageBase64}" /&gt;
    /// </summary>
    public string? ChartImageBase64 { get; set; }

    /// <summary>
    /// Chart type used for visualization: "bar", "line", "pie", "scatter", or null if no chart
    /// </summary>
    public string? ChartType { get; set; }
}